spring:
  datasource:
    username: mfturkcan
    password:
    url: jdbc:postgresql://localhost:5432/nereye
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: auto
